[package]
name = "syncflow-examples"
version.workspace = true
edition.workspace = true

[[example]]
name = "demo"
path = "demo.rs"

[[example]]
name = "server_client"
path = "server_client.rs"

[dependencies]
syncflow-core.workspace = true
syncflow-storage.workspace = true
syncflow-sync.workspace = true
tokio.workspace = true